server:
  port: 8080

spring:
  application:
    name: wzyTest
  datasource:
    dynamic:
      primary: wzy
      strict: false
      datasource:
        wzy:
          url: jdbc:mysql://127.0.0.1:3306/wzy_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: ENC(esyjb8RJAcQvzhFYnf/RBl/6DOqIoTA6Sb6kiCmpJGuCVLPHc94eE/8fUmRf3fhCXIPyfF7DDT9j8XCtUIadrw==)
        slave:
          url: jdbc:mysql://127.0.0.1:3306/slave_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: ENC(esyjb8RJAcQvzhFYnf/RBl/6DOqIoTA6Sb6kiCmpJGuCVLPHc94eE/8fUmRf3fhCXIPyfF7DDT9j8XCtUIadrw==)
  redis:
    host: 127.0.0.1
    port: 6379

minio:
  url: http://127.0.0.1:9000
  accessKey: igjkVGTriynTCRdC0I9U
  secretKey: KO58U83ulsZs3puKJNIGrAiKEvl14oUPwhAeW5qX

logging:
  level:
    root: INFO
#    org.springframework.cache: INFO
#    org.springframework.boot.autoconfigure.cache: INFO
#    com.github.benmanes.caffeine.cache: INFO

#mybatis-plus:
#  configuration:
#    # 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

